services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    # command: uwsgi --http :8000 --module server.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
