services:
  web:
    build:
      context: django
    restart: always
    volumes:
      - ./django:/code
    ports:
        - "8000:8000"
    networks:
      - backnet
      - frontnet
    command: python manage.py runserver 0.0.0.0:8000
  proxy:
    build: proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - frontnet
networks:
    frontnet:
    backnet:
