services:
  web:
    build:
      context: django
    restart: always
    volumes:
      - ./django:/code
      - ./staticfiles/:/code/staticfiles
    ports:
      - "8000:8000"
    networks:
      - backnet
      - frontnet
    env_file:
      - ./django/.env
    command: gunicorn --bind :8000 app.wsgi:application
  proxy:
    build: proxy
    restart: always
    volumes:
      - ./staticfiles/:/code/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - frontnet
networks:
  frontnet:
  backnet:
